[profile.default]
optimizer_runs = 200
via_ir = false
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out" },
]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

[rpc_endpoints]
polygonpos = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
ethereum = "${MAINNET_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsctest = "${BSCTEST_RPC_URL}"

[etherscan]
polygonpos = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
mumbai = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
bsctest = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}", url = "https://blockscout.com/poa/xdai/api" }

[profile.default.fuzz]
runs = 100
seed = "0x4444"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.ci.fuzz]
runs = 1000

[profile.ci]
fuzz_runs = 100000
solc = "./bin/solc-static-linux"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
